### ISSUE TITLE
Using ConnectionManager stalls bull

### ISSUE THREAD

**Issue by ce07c3** [electricimp/ConnectionManager#11] opened 2016-10-11 14:35 UTC

**Comment by ppetrosh** [comment] 2016-10-11 18:32
Carl, can you please provide more details on what's the issue is?

There is a accidental disconnect issue which is going to be fixed with https://github.com/electricimp/ConnectionManager/pull/7. Is it what you mean?

**Comment by ce07c3** [comment] 2016-10-11 18:38
I don't know. Using ConnectionManager means bull messages don't arrive server side. Somehow there seems to be a hickup. 

Removing it and everything is fine again.

**Comment by ppetrosh** [comment] 2016-10-11 18:40
Got it, thanks.

**Comment by ppetrosh** [comment] 2016-10-12 22:20
@ce07c3, can you please verify that the bug is fixed on the latest master (it's not staged yet, so you have to copy and paste the library code into your application to make sure you get the latest version).

Thank you!

**Comment by ce07c3** [comment] 2016-10-14 13:02
Will do once I get the chance (OOO today). Thanks, Pavel.

**Comment by ratneshdeepak** [comment] 2017-06-10 05:14
@ppetrosh @ce07c3 The issue is still open since (Oct 14 2016) has the fix not been verified yet.

**Comment by ppetrosh** [comment] 2017-06-10 17:11
@ratneshdeepak do you still have any issues? I would close this one as the fixes has been integrated/verified on our side long ago. If there is anything else please let me know and file new issues with details and code snippets on how to reproduce the problem. Thanks!

**Closed by ppetrosh** 2017-06-10 17:11 UTC
